# Site settings
title: Chris Lewis
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chris Lewis
user_description: I have recently received a Master of Science in Computer Science from the University of Massachusetts Lowell, with a focus in machine learning and data science. I am driven by a deep passion for leveraging the power of machine learning to solve complex problems and make a positive impact on others. Specifically, my focus lies in the application of deep learning techniques to advance the fields of natural language processing and computer vision. Currently, I am seeking positions as a machine learning engineer/data scientist.
user_title: Python | Machine Learning | Data Science
github_username:  lewisc4
linkedin_username: christopherlewis10
email: clewis7744@gmail.com

exclude: ['package.json', 'src', 'node_modules', 'vendor']

